"use client";
import Link from "next/link";import {useParams} from "next/navigation";import {ChangeEvent,useEffect,useState} from "react";import {Shell} from "@/components/Shell";import {Confirm,Modal} from "@/components/Modal";import {Toast} from "@/components/Toast";import {Pagination} from "@/components/Pagination";import {api,download} from "@/lib/api";
type Zone={id:number;name:string;comment:string;zone_type:string};type RecordItem={id:number;name:string;type:string;value:string;ttl:number;routing_policy:string};type Result={items:RecordItem[];total:number;page:number;page_size:number};const types=['A','AAAA','CNAME','MX','NS','PTR','SRV','TXT','CAA'];
export default function Records(){const {id}=useParams<{id:string}>(),[zone,setZone]=useState<Zone|null>(null),[data,setData]=useState<Result>({items:[],total:0,page:1,page_size:10}),[search,setSearch]=useState(''),[type,setType]=useState(''),[page,setPage]=useState(1),[modal,setModal]=useState<RecordItem|null|undefined>(),[remove,setRemove]=useState<RecordItem|null>(null),[selected,setSelected]=useState<number[]>([]),[importing,setImporting]=useState(false),[bind,setBind]=useState(''),[toast,setToast]=useState<string|null>(null),[error,setError]=useState('');
 const load=()=>api<Result>(`/hosted-zones/${id}/records?search=${encodeURIComponent(search)}&type=${type}&page=${page}`).then(d=>{setData(d);setSelected([])}).catch(e=>setError(e.message));
 useEffect(()=>{api<Zone>(`/hosted-zones/${id}`).then(setZone).catch(e=>setError(e.message))},[id]);useEffect(()=>{const h=setTimeout(load,150);return()=>clearTimeout(h)},[id,search,type,page]);useEffect(()=>{const create=()=>setModal(null);addEventListener('route53:create',create);return()=>removeEventListener('route53:create',create)},[]);
 const save=async(v:Record<string,string>)=>{try{const body={...v,ttl:Number(v.ttl)};if(modal)await api(`/hosted-zones/${id}/records/${modal.id}`,{method:'PUT',body:JSON.stringify(body)});else await api(`/hosted-zones/${id}/records`,{method:'POST',body:JSON.stringify(body)});setModal(undefined);setToast(`Record ${modal?'updated':'created'} successfully`);load()}catch(e){setError(e instanceof Error?e.message:'Unable to save')}};
 const toggle=(recordId:number)=>setSelected(x=>x.includes(recordId)?x.filter(v=>v!==recordId):[...x,recordId]);
 const importFile=(e:ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>setBind(String(reader.result||''));reader.readAsText(file)};
 return <Shell><Toast message={toast}/><div className="breadcrumbs"><Link href="/dashboard">Route 53</Link> <span>›</span> <Link href="/hosted-zones">Hosted zones</Link> <span>›</span> {zone?.name||'Loading...'}</div>
 <div className="page-heading"><div><h1>{zone?.name||'Hosted zone'}</h1><p>Hosted zone details <span className="dot-sep">•</span> {zone?.zone_type||'Public'}</p></div><div className="heading-actions"><button className="secondary" onClick={()=>setImporting(true)}>Import zone file</button><button className="secondary" onClick={()=>download(`/hosted-zones/${id}/export?format=json`,`${zone?.name||'zone'}.json`)}>Export JSON</button><button className="secondary" onClick={()=>download(`/hosted-zones/${id}/export?format=bind`,`${zone?.name||'zone'}.zone`)}>Export BIND</button><button className="primary" onClick={()=>setModal(null)}>Create record</button></div></div>
 {error&&<div className="error">{error}</div>}
 <section className="aws-card"><div className="card-header"><div><h2>Records <span className="info-dot">i</span></h2><p>Records define how Route 53 responds to DNS queries for this hosted zone.</p></div><button className="link-button-dark">Switch to wizard</button></div>
 {selected.length>0&&<div className="bulkbar"><b>{selected.length} selected</b><button className="danger" onClick={()=>setRemove({id:-1,name:'selected records',type:'',value:'',ttl:0,routing_policy:''})}>Delete</button><button className="text-button" onClick={()=>setSelected([])}>Clear selection</button></div>}
 <div className="table-toolbar"><input data-console-search className="search" placeholder="Search records" value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}}/><select className="filter" value={type} onChange={e=>{setType(e.target.value);setPage(1)}}><option value="">All record types</option>{types.map(t=><option key={t}>{t}</option>)}</select><span className="result-count">{data.total} record{data.total===1?'':'s'}</span></div>
 <table><thead><tr><th className="check-col"><input className="checkbox" type="checkbox" aria-label="Select all records" checked={!!data.items.length&&selected.length===data.items.length} onChange={e=>setSelected(e.target.checked?data.items.map(r=>r.id):[])}/></th><th>Record name</th><th>Type</th><th>Value / Route traffic to</th><th>TTL (seconds)</th><th>Routing policy</th><th></th></tr></thead><tbody>{data.items.map(r=><tr key={r.id}><td><input className="checkbox" type="checkbox" checked={selected.includes(r.id)} onChange={()=>toggle(r.id)}/></td><td><span className="record-name">{r.name}</span></td><td><span className="type">{r.type}</span></td><td className="value">{r.value}</td><td>{r.ttl}</td><td>{r.routing_policy}</td><td className="row-actions"><button className="table-action" onClick={()=>setModal(r)}>Edit</button><button className="table-action danger-text" onClick={()=>setRemove(r)}>Delete</button></td></tr>)}{!data.items.length&&<tr><td colSpan={7} className="empty">No records match this view.</td></tr>}</tbody></table><Pagination page={page} total={data.total} size={data.page_size} setPage={setPage}/></section>
 {modal!==undefined&&<Modal title={modal?'Edit record':'Quick create record'} initial={modal||{type:'A',ttl:'300',routing_policy:'Simple'}} fields={[{key:'name',label:'Record name',hint:`Keep blank for the root domain or use a name under ${zone?.name||'this zone'}`},{key:'type',label:'Record type',options:types},{key:'value',label:'Value / Route traffic to'},{key:'ttl',label:'TTL (seconds)',type:'number'},{key:'routing_policy',label:'Routing policy',options:['Simple']}]} onClose={()=>setModal(undefined)} onSave={save}/>} 
 {remove&&<Confirm title="Delete record" body={remove.id===-1?`Permanently delete ${selected.length} selected records?`:`Delete the ${remove.type} record ${remove.name}?`} onClose={()=>setRemove(null)} onConfirm={async()=>{if(remove.id===-1)await api(`/hosted-zones/${id}/records/bulk-delete`,{method:'POST',body:JSON.stringify({ids:selected})});else await api(`/hosted-zones/${id}/records/${remove.id}`,{method:'DELETE'});setRemove(null);setToast('Record deletion completed');load()}}/>}
 {importing&&<div className="overlay"><div className="modal"><div className="modal-heading"><h2>Import BIND zone file</h2><button className="icon" onClick={()=>setImporting(false)}>×</button></div><div className="modal-body"><label>Zone file<input type="file" accept=".zone,.bind,.txt" onChange={importFile}/></label><label>Or paste BIND records<textarea value={bind} onChange={e=>setBind(e.target.value)} placeholder={'$ORIGIN example.com.\nwww 300 IN A 192.0.2.10'} rows={9}/></label></div><div className="modal-footer"><button className="secondary" onClick={()=>setImporting(false)}>Cancel</button><button className="primary" disabled={!bind.trim()} onClick={async()=>{try{const out=await api<{imported:number}>(`/hosted-zones/${id}/records/import-bind`,{method:'POST',body:JSON.stringify({text:bind})});setImporting(false);setToast(`${out.imported} record(s) imported`);load()}catch(e){setError(e instanceof Error?e.message:'Import failed')}}}>Import records</button></div></div></div>}
 </Shell>}
